### ISSUE TITLE
PR 템플릿

### ISSUE THREAD

**Issue by mquat** [mquat/cafeLab#1]
- pull request 에 사용될 template 업데이트
- 해당 파일을 따로 분류해두기 위한 `.github` 디렉토리 생성

**Comment by jacob-f-lab** [comment]
https://github.com/features/actions
디렉토리 만드시는 김에 자동화된 테스트(github action) 관련해서 읽어보시는것도 권해드립니다

**Comment by mquat** [comment]
넵 감사합니다!
